### ISSUE TITLE
Erlang 19

### ISSUE THREAD

**Issue by chvanikoff** [msaraiva/docker-alpine#13]
First of all, thanks for all the job done related to alpine-erlang and alpine-elixir, it's really much appreciated!
But here is one question as follows from the issue title: is there any ETA for Erlang 19 built on top of Alpine?

**Comment by msaraiva** [comment]
@chvanikoff I'm already working on the patch for the Erlang 19.0.1 package for Alpine. The package will be available on "edge" soon, however, since the docker images are based only on stable releases, you will need to wait for Alpine 3.5. An alternative would be to build your on docker image based on "edge". This could be ok for development but I wouldn't recommend for production.

**Comment by chvanikoff** [comment]
Thanks for the update, I already see it on Edge. I'm not planning to use it in production so far, just playing around and mostly for dev purpose, however looking forward to seeing 3.5 in November 😄

**Comment by chvanikoff** [comment]
@msaraiva by the way, I found a way to install the package on `Alpine:3.4` instead of `:edge`, but would like to hear from you on downsides of such approach
`apk add 'erlang=19.0.1-r0' --no-cache --repository http://nl.alpinelinux.org/alpine/edge/community`

**Comment by edevil** [comment]
@chvanikoff Have you had any problems running Erlang 19 on Alpine 3.4?

**Comment by chvanikoff** [comment]
@edevil no but I didn't really spent much time with it. Instead I decided to wait until next Alpine release to reconsider it as OS of my choice, since I need to have dev and prod envs to be the same.
